language: ruby
rvm:
- 2.0.0
branches:
  only:
  - master
script: rake travis
env:
  global:
    secure: "QInDBXzpGlpDjIBj70VY8jgnmum5pOPE+DVAMmHFGO1QRKUdnI09R5Jw3+EHCzEqjzCDV5d74HyUjaULyba/euXYJtTM4pEAMkh1Tjc/B67uk8inH+KTa2dCbSeBjWOrdE+DyexoQggCbe65KMa7JpK6U04rDrppgPxbQTnVl4Q="
